version: 2
jobs:
  build:
    working_directory: ~/cci-hale-cryptopals
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: cci-hale-cryptopals-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: cci-hale-cryptopals-{{ checksum "project.clj" }}
      - run: lein test2junit
      - run: lein uberjar
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: target/uberjar/cci-hale-cryptopals.jar
          destination: uberjar
